apiVersion: v1
kind: Service
metadata:
  name: {{ include "aks-spot-instance-tolerator.fullname" . }}
  labels:
    {{- include "aks-spot-instance-tolerator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aks-spot-instance-tolerator.selectorLabels" . | nindent 4 }}
