apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "aks-spot-instance-tolerator.fullname" . }}-webhook
webhooks:
  - name: pod-mutating-webhook.k8s.io
    failurePolicy: Ignore
    clientConfig:
      service:
        name: {{ include "aks-spot-instance-tolerator.fullname" . }}
        namespace: {{ .Release.Namespace | quote }}
        path: /mutate
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchExpressions:
        - key: name
          operator: NotIn
          values:
            - {{ .Release.Namespace }}
    objectSelector:
      matchExpressions:
        - key: "app.kubernetes.io/name"
          operator: NotIn
          values:
            - {{ include "aks-spot-instance-tolerator.name" . }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
