apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "aks-spot-instance-tolerator.fullname" . }}-clusterrole
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "update"]
  resourceNames: ["{{ include "aks-spot-instance-tolerator.fullname" . }}-webhook"]
