apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aks-spot-instance-tolerator.fullname" . }}-crb
subjects:
- kind: ServiceAccount
  name: {{ include "aks-spot-instance-tolerator.serviceAccountName" . }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ include "aks-spot-instance-tolerator.fullname" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io