apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aks-spot-instance-tolerator.fullname" . }}-rb
subjects:
- kind: ServiceAccount
  name: {{ include "aks-spot-instance-tolerator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: {{ include "aks-spot-instance-tolerator.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
