name: Build and Push with ko
on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Check if commit is tagged
        id: check_tag
        run: |
          if [ -z "${GITHUB_REF##refs/tags/*}" ]; then
            echo "This commit is tagged."
          else
            echo "No tag associated with this commit."
            exit 1
          fi

      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: run tests
        run: go test ./...

      - uses: ko-build/setup-ko@v0.6
      # - run: ko build
      - name: Generate and upload release.yaml
        run: |
          ./run-build.sh
      - uses: stefanzweifel/git-auto-commit-action@v5