name: Build and Push with ko
on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - uses: actions/checkout@v3
      - name: run tests
        run: go test ./...

      - uses: ko-build/setup-ko@v0.6
      - run: ko build