name: Build and Push with ko
on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - uses: actions/checkout@v3
      - name: run tests
        run: go test ./...

      - uses: ko-build/setup-ko@v0.6
      # - run: ko build
      - name: Generate and upload release.yaml
        run: |
          ./run-build.sh
      - uses: stefanzweifel/git-auto-commit-action@v5