name: Build and Push with ko
on:
  push:
    branches:
      - main
    # tags:
    #   - 'release*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: run tests
        run: go test ./...

      - uses: ko-build/setup-ko@v0.6
      - name: ko build
        run: |
          ./run-build.sh
  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: ko-build/setup-ko@v0.6
      - name: prepare delivery
        run: |
          mkdir delivery
          cp -r helm/aks-spot-instance-tolerator/ delivery/
          ko resolve -f helm/aks-spot-instance-tolerator/values.yaml --bare > delivery/aks-spot-instance-tolerator/values.yaml
      - name: Get tags
        run: git fetch --tags origin
      - name: Check for release tag
        id: check_tag
        run: |
          TAG=$(git tag --contains HEAD | grep '^release' || false)
          echo "debug 1"
          echo $TAG
          if [ -n "$TAG" ]; then
            echo "debug 2"
            echo "release_tag=true" >> $GITHUB_ENV
          else
            echo "debug 2"
            echo "release_tag=false" >> $GITHUB_ENV
          fi
      - name: Pushes to another repository
        if: env.release_tag == 'true'
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'delivery/aks-spot-instance-tolerator'
          target-directory: 'charts/aks-spot-instance-tolerator'
          destination-github-username: 'stein-solutions'
          destination-repository-name: 'helm-charts'
          user-email: chart-bot@stein.solutions
          target-branch: main
